include:
  - component: "gitlab.com/it-erben/components/pdf-publisher/build-publish@1.6.0"
  - component: "gitlab.com/it-erben/components/linters/lychee-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/linters/yaml-lint@1.3.0"
  - component: "gitlab.com/it-erben/components/linters/markdown-lint@1.3.0"

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - lint
  - build
  - verify
  - release
  - deploy

java:
  stage: verify
  image: maven:3.9.12-eclipse-temurin-25
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
  script:
    - mvn verify
  rules:
    - if: $CI_MERGE_REQUEST_ID
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
