<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>tech.erben</groupId>
    <artifactId>sb-advanced</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <spring-boot.version>3.5.8</spring-boot.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <maven-compiler-plugin.version>3.12.1</maven-compiler-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <modules>
        <module>sb-advanced-autoconfiguration</module>
        <module>sb-advanced-actuator</module>
        <module>sb-advanced-testing</module>
        <module>sb-advanced-web</module>
        <module>sb-advanced-starter</module>
        <module>sb-advanced-reactive</module>
        <module>sb-advanced-security-basic</module>
        <module>sb-advanced-data-mongodb</module>
        <module>sb-advanced-data-redis</module>
        <module>sb-advanced-data-jpa</module>
        <module>sb-advanced-vault</module>
        <module>sb-advanced-messaging-amqp</module>
        <module>sb-advanced-security-oauth2</module>
    </modules>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.hubspot.maven.plugins</groupId>
                <artifactId>prettier-maven-plugin</artifactId>
                <version>0.21</version>
                <configuration>
                    <prettierJavaVersion>2.0.0</prettierJavaVersion>
                    <printWidth>90</printWidth>
                    <tabWidth>4</tabWidth>
                    <useTabs>false</useTabs>
                    <ignoreConfigFile>true</ignoreConfigFile>
                    <ignoreEditorConfig>true</ignoreEditorConfig>
                    <!-- Use <inputGlobs> to override the default input patterns -->
                    <inputGlobs>
                        <!-- These are the default patterns, you can omit <inputGlobs> entirely unless you want to override them -->
                        <inputGlob>src/main/java/**/*.java</inputGlob>
                        <inputGlob>src/test/java/**/*.java</inputGlob>
                    </inputGlobs>
                </configuration>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>write</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
