spring:
  application:
    name: actuator-task

info:
  app:
    name: Actuator Task
    version: 1.0.0
    commit: local-dev

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,metrics,loggers,prometheus,featureToggle
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    propagation:
      type: b3

logging:
  level:
    tech.erben.springboot.actuator: INFO
