<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>tech.erben</groupId>
    <artifactId>sb-advanced-solutions</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <spring-boot.version>3.5.8</spring-boot.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <modules>
        <module>sb-advanced-autoconfiguration-solution</module>
        <module>sb-advanced-actuator-solution</module>
        <module>sb-advanced-testing-solution</module>
        <module>sb-advanced-starter-solution</module>
        <module>sb-advanced-data-mongodb-solution</module>
        <module>sb-advanced-data-redis-solution</module>
        <module>sb-advanced-data-jpa-solution</module>
    </modules>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
