spring.application.name=sb-advanced-tracing-demo

spring.datasource.url=jdbc:h2:mem:tracing-demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.tracing.export.otlp.transport=http

management.tracing.enabled=true
logging.level.io.opentelemetry.exporter.zipkin=DEBUG
logging.level.io.micrometer.tracing=DEBUG
