spring:
  application:
    name: actuator-demo

info:
  app:
    name: Actuator Demo
    version: 1.0.0
    commit: local-demo

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,metrics,loggers,prometheus,featureToggle
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    tech.erben.springboot.actuatordemo: INFO
